### ISSUE TITLE
Case control fails when genotypes have readgroups in header

### ISSUE THREAD

**Issue by EAC92** [DBHi-BiC/snpEff#3]
I have been using the casecontrol tool within snpEFF as part of the SnpSift package to great success in a multi-genotype vcf file created as an output of mpileup, where the first 3 columns are my cases, and the latter by control. However, this doesn't work when my genotypes are labelled with their readgroups, as required by freebayes when calling variants.

How can I get it to interpret these correctly/remove them entirely to get the commands to run?

**Comment by leipzig** [comment]
this is a fork of snpeff - I would try https://github.com/pcingola/SnpEff or biostars.org
